[package]
name = "mercurial-amm"
version = "0.1.3"
description = "Created with Anchor"
edition = "2021"
license = "MIT"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib"]
name = "amm"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
mercurial-vault = { git="https://github.com/mercurial-finance/vault-sdk", rev="a615dbdc64c25c2e25824ddd9b8fce11b90a3d7f", features = ["cpi"] }

